version: "3"
services:
  api:
    image: node:11.13.0-alpine
    container_name: api
    volumes:
      - .:/app
    environment:
      - NODE_ENV=dev
      - SECRET=5h0p1fY
      - IMAGES_URL=http://localhost:3001
    working_dir: /app
    command: npm run start:local
    network_mode: host
  mongo:
    container_name: mongo
    image: mongo
    network_mode: host
    logging:
      driver: none